# nvuv default config file

# For multi GPU systems, first identify the GPU indexes
# run: `nvuv get gpu`.
# Then add a section for each GPU in their respective order.

# Comment out any option to keep it at default value

# GPU0
[[gpu]]
# power_limit = 175 # watts
# gpu_offset = 200 # MHz
# mem_offset = 400

# [gpu.gpu_clocks.locked]
# If min value is not provided, it will be set to the lowest
# supported clock
# Max value is required
# max = 2400 # MHz
# min = 180 # MHz

# [gpu.mem_clocks.locked]
# max = 1234
# min = 123

# Reset clocks to default value
# Useful for switching between different configs for different use cases
# [gpu.gpu_clocks]
# reset = 1
# [gpu.mem_clocks]
# reset = 1

# For multi GPUs add more section as needed

# GPU1
# [[gpu]]
# …
