name: Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for the release'
        required: false
        default: dev
      publish:
        type: boolean
        description: Publish Release
        required: true
        default: false
  push:
    tags:
      - 'v*'

jobs:
  build-arch:
    name: Build Arch Linux (x86_64)
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
      options: --privileged

    env:
      ARTIFACT_DIR: artifact
      BINARY_NAME: nvuv-linux-x86_64

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Update system
        run: |
          pacman -Syu --noconfirm

      - name: Install system deps
        run: |
          pacman -S --noconfirm nvidia-utils

      - name: Install Zig master
        uses: mlugg/setup-zig@v2
        with:
          version: master

      - name: Build
        run: |
          zig build -Doptimize=ReleaseSmall --search-prefix /usr
          ls -lh zig-out/bin/

      - name: Prepare artifacts
        run: |
          mkdir -p ${{ env.ARTIFACT_DIR }}
          cp zig-out/bin/nvuv ${{ env.ARTIFACT_DIR }}/${{ env.BINARY_NAME }}
          cd ${{ env.ARTIFACT_DIR }}
          sha256sum ${{ env.BINARY_NAME }} > ${{ env.BINARY_NAME }}.sha256sum
          ls -lh

      - name: Print build info
        run: |
          echo "--------------------------------------------"
          echo "SHA256 Checksum:"
          echo "--------------------------------------------"
          cat ${{ env.ARTIFACT_DIR }}/${{ env.BINARY_NAME }}.sha256sum
          echo "--------------------------------------------"
          echo "binary name: ${{ env.BINARY_NAME }}"
          echo "file size  : $(du -h ${{ env.ARTIFACT_DIR }}/${{ env.BINARY_NAME }} | cut -f1)"
          echo "--------------------------------------------"

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: nvuv-linux-x86_64
          path: ${{ env.ARTIFACT_DIR }}
          retention-days: 7
          if-no-files-found: error

  release:
    if: startsWith(github.ref, 'refs/tags/v') || inputs.publish == true
    name: Create GitHub Release
    needs: build-arch
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v6
        with:
          name: nvuv-linux-x86_64
          path: release-assets

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ inputs.tag_name || github.ref_name }}
          tag_name: ${{ inputs.tag_name || github.ref_name }}
          draft: false
          files: |
            release-assets/*

  aur-publish:
    if: startsWith(github.ref, 'refs/tags/v')
    name: Publish AUR package
    needs: release
    runs-on: ubuntu-latest
    env:
      PKGBUILD: ./.pkg/arch/PKGBUILD
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Get tarball sha256sum
        id: tarball
        run: |
          curl -LfsSo sources.tar.gz "https://github.com/doums/nvuv/archive/refs/tags/${{ github.ref_name }}.tar.gz"
          sha256sum=$(sha256sum sources.tar.gz | awk '{print $1}')
          echo "tarball sha256sum: $sha256sum"
          echo "sha256sum=$sha256sum" >> "$GITHUB_OUTPUT"

      - name: Update PKGBUILD
        env:
          RELEASE_TAG: ${{ github.ref_name }}
          SHA256SUM: ${{ steps.tarball.outputs.sha256sum }}
        run: |
          # strip v prefix
          version="${RELEASE_TAG#v}"
          # ⚠ Dashes are not allowed in package version, replace any - by _
          pkgver=${version//-/_}
          echo "pkgver: $pkgver"
          # update version and sha256sum
          sed -i "s/pkgver=.*/pkgver=$pkgver/" ${{ env.PKGBUILD }}
          sed -i "s/sha256sums=(.*)/sha256sums=('$SHA256SUM')/" ${{ env.PKGBUILD }}
          cat ${{ env.PKGBUILD }}

      - name: Publish
        uses: KSXGitHub/github-actions-deploy-aur@v4.1.2
        with:
          pkgname: nvuv
          pkgbuild: ${{ env.PKGBUILD }}
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_KEY }}
          commit_message: ${{ github.ref_name }}
